---
- hosts: all
  tasks:
  - name: 'Instala pacotes de dependência do sistema operacional'
    apt:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - php5
      - apache2
      - libapache2-mod-php5
      - php5-gd
      - libssh2-php
      - php5-mcrypt
      - mysql-server-5.6
      - python-mysqldb
      - php5-mysql
  - name: 'Cria o banco do MySQL'
    mysql_db: 
      name: wordpress_db
      login_user: root
      state: present
  - name: 'Cria o usuário do banco de dados'
    mysql_user:
      login_user: root
      name: wordpress_user
      password: 12345
      priv: 'wordpress_db.*:ALL'
      state: present
  - name: 'Download do arquivo de instalação do Wordpress'
    get_url:
      url: 'https://wordpress.org/latest.tar.gz'
      dest: '/tmp/wordpress.tar.gz'
  - name: 'Descompacta o arquivo do Wordpress'
    unarchive:
      src: '/tmp/wordpress.tar.gz'
      dest: '/var/www/'
      remote_src: yes
    become: yes
